CONFIG_DISPLAY=y
CONFIG_LOG=y
CONFIG_SPI=y
CONFIG_DEBUG_OPTIMIZATIONS=y
CONFIG_DEBUG_THREAD_INFO=y
CONFIG_THREAD_RUNTIME_STATS=y
CONFIG_NORITAKE_GU_VFD=y
CONFIG_GU_VFD_USE_SPI_TRANSFER_FOR_WRITE=y
CONFIG_HEAP_MEM_POOL_SIZE=1024

